apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "first-chart.fullname" . }}
  labels:
    {{- include "first-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "first-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "first-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          ports:
            - name: web
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: first-config
            - secretRef:
                name: first-secret
