apiVersion: v1
kind: Service
metadata:
  name: {{ include "first-chart.fullname" . }}
  labels:
    {{- include "first-chart.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    {{- include "first-chart.selectorLabels" . | nindent 4 }}
